<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure to delete this item?' => '',
    'Css Class' => '',
    'ID' => '',
    'Name' => '',
    'Owner' => '',
    'Sortorder' => '',
    'Админка' => 'Admin',
    'Выйти' => 'Logout',
    'Главная' => 'Home',
    'О проекте' => 'About us',
    'Обратная связь' => 'Feedback',
    'Отправить' => 'Submit',
    'Профиль' => 'Profile',
    '<a href="{url}">Восстановить пароль</a>' => 'If you forgot your password you can <a href="{url}">reset it</a>.',
    '<a href="{url}">Регистрация</a>' => 'If you don\'t have account yet, please <a href="{url}">signup</a>.',
    'Адрес уже используется другим пользователем.' => 'Email already taken',
    'Войти' => 'Login',
    'Вход на сайт' => 'Login',
    'Вы уверены, что хотите удалить этот элемент?' => 'Are you sure to delete this item?',
    'Заполните все поля для входа на сайт:' => 'Please fill out the following fields to login:',
    'Запомнить меня' => 'Remember me',
    'Изменение пароля' => 'Change password',
    'Имя' => 'Name',
    'Не существует пользователя с таким адресом' => 'There is no user with such email.',
    'Неправильный текущений пароль.' => 'Wrong current password',
    'Новый пароль' => 'New password',
    'Обновлен' => 'Updated',
    'Пароль' => 'Password',
    'Перейдите по ссылке, чтобы сбросить пароль:' => 'Follow the link below to reset your password:',
    'Проверочный код' => 'Verification code',
    'Сброс пароля для {user}' => 'Password reset for {user}',
    'Создан' => 'Created',
    'Сообщение' => 'Message',
    'Статус' => 'Status',
    'Текущий пароль' => 'Current password',
    'Тема' => 'Subject',
];
