#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

use yii\helpers\ArrayHelper;

$env = 'prod';
foreach ($_SERVER['argv'] as $key => $arg) {
	if (strpos($arg,'env=')=== 0) {
		$env = substr($arg, 4);
		$_SERVER['argc']--;
		unset($_SERVER['argv'][$key]);
	}
}

echo 'Env=',$env,PHP_EOL;

define('YII_ENV', $env);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');
$configWeb = require(__DIR__ . '/config/web.php');

$config = ArrayHelper::merge($config, $configWeb);

if('prod'!=YII_ENV) {
    $configEnv = require(__DIR__ . '/config/' . YII_ENV . '.php');
    $config = ArrayHelper::merge($config, $configEnv);
}

unset($config['modules']);
unset($config['components']['request']);
unset($config['components']['errorHandler']);
unset($config['components']['user']);
unset($config['components']['session']);
unset($config['bootstrap']);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
