<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'О нас',
    'Account' => 'Профиль',
    'Account Edit' => 'Редактировать профиль',
    'Add child' => 'Добавить потомка',
    'Are you sure to delete this item?' => 'Вы действительно хотите удалить этот элемент?',
    'Author' => 'Автор',
    'Authorization failed' => 'Авторизация не удалась',
    'Avatar' => 'Аватар',
    'Back to website' => 'Назад к сайту',
    'Categories' => 'Категории',
    'Change Password' => 'Сменить пароль',
    'Change password' => 'Сменить пароль',
    'Check your email for further instructions.' => 'Проверьте почтовый ящик для дальнейших инструкций',
    'Click this link to reset your password:' => 'Нажмите эту ссылку чтобы сбросить пароль',
    'Contact' => 'Обратная связь',
    'Content' => 'Контент',
    'Control Panel' => 'Панель управления',
    'Create' => 'Создать',
    'Create, update, delete categories' => 'Добавить, редактировать, удалить категории',
    'Create, update, delete pages' => 'Добавить, редактировать, удалить страницы',
    'Created' => 'Дата создания',
    'Created At' => 'Дата создания',
    'Css Class' => 'CSS класс',
    'Current password' => 'Текущий пароль',
    'Edit user information' => 'Редактировать пользовательскую информацию',
    'Email' => 'Email',
    'Email already in use by another user.' => 'Email уже используется другим пользователем',
    'Home' => 'Главная',
    'ID' => 'ID',
    'If you don\'t have account yet, please <a href="{url}">signup</a>.' => 'Если у вас еще нет аккаунта, пожалуйста <a href="{url}">зарегистрируйтесь</a>.',
    'If you forgot your password you can <a href="{url}">reset it</a>.' => 'Забыли пароль? <a href="{url}">Восстановление пароля</a>.',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Manage' => 'Управление',
    'Manage Categories' => 'Управление категориями',
    'Manage Pages' => 'Управление страницами',
    'Max size' => 'Максимальный размер',
    'Message' => 'Сообщение',
    'Mime-type' => 'MIME-тип',
    'Move down' => 'Вниз',
    'Move up' => 'Вверх',
    'Name' => 'Название',
    'New password' => 'Новый пароль',
    'New password was saved.' => 'Новый пароль сохранен.',
    'Owner' => 'Владелец',
    'Pages' => 'Страницы',
    'Password' => 'Пароль',
    'Password reset for user {user}' => 'Сброс пароля для пользователя {user}',
    'Password were sended to {email}. Please check your email (including spam box)' => 'Пароль был отправлен на {email}. Проверьте почту (в том числе папку "Спам")',
    'Please choose your new password:' => 'Выберите новый пароль:',
    'Please fill out the following fields to login:' => 'Заполните следующие поля для входа:',
    'Please fill out the following fields to signup:' => 'Заполните следующие поля для регистрации:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Введите свой email. На него будет отправлена ссылка на сброс пароля.',
    'Registration on {appname}' => 'Регистрация на {appname}',
    'Remember me' => 'Запомнить меня',
    'Request password reset' => 'Запрос смены пароля',
    'Reset password' => 'Смена пароля',
    'Save' => 'Сохранить',
    'Send' => 'Отправить',
    'Signup' => 'Регистрация',
    'Size' => 'Размер',
    'Slug' => 'ЧПУ',
    'Social' => 'Соц.сети',
    'Sorry, we are unable to reset password for email provided.' => 'Невозможно сменить пароль для этого email',
    'Sortorder' => 'Порядок сортировки',
    'Status' => 'Статус',
    'Subject' => 'Тема',
    'Submit' => 'Отправить',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Спасибо за обращение. Мы ответим вам в ближайше время.',
    'Title' => 'Заголовок',
    'Unsupported image type' => 'Неподдерживаемый тип изображения',
    'Update' => 'Редактировать',
    'Updated' => 'Обновлено',
    'Verify Code' => 'Код подтверждения',
    'Version' => 'Версия',
    'Website' => 'Веб-сайт',
    'Wrong current password' => 'Неверный текущий пароль',
    'Wrong email or password.' => 'Неверный email или пароль',
    'Wrong image type' => 'Неверный тип изображения',
    'Your Name' => 'Имя',
    'or' => 'или',
];
